debugger: gdb
compiler:
  cc: gcc
  cxx: g++

# These will be given to CMake configuring.
cmake:
  definitions:
    - CFG1=cfg1
    - CFG2=cfg2
    - invalid: which is silently dropped during parsing, and is tested

docker:
  image: test-buildenv
  name: cica
  env:
    - CICA=cica
    - KUTYA=kutya
    - invalid: which is silently dropped during parsing, and is tested
  remove: true
  stdout: true
  stderr: true
