name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Rust
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y

    - name: Install C++ (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake

    - name: Build
      run: cargo build

    - name: Unit Test
      run: cargo test

    - name: Build release
      run: cargo build --release

    - name: Regression Test
      run: ./tests/reg-test.sh
